### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by awenelo** [WCI-Computer-Science/WCI-Walks#11]
- [x] Add a "like" button that notifies someone when someone likes their profile:
        Likes: 20 (+2 since last time)
- [x] Show your leaderboard position on the profile page
- [x] Show top 30 instead of 20 on the leaderboard

**Comment by scott-22** [comment]
Removed profile pics, it might be too much space in DB

**Comment by awenelo** [comment]
All done!
